version: "3"

services:
  workspace:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: steven_lara_framework
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
        - .:/var/www/html
        - ./docker/nginx_log:/var/log/nginx
        - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
        - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
    links:
        - mysql

  mysql:
    image: mysql:5.6
    container_name: steven_lara_mysql
    ports:
      - "3308:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
